version: "3.9"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: sajid
      POSTGRES_PASSWORD: sajid123
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  shopping-backend:
    build: .
    container_name: shopping-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/inventory
      SPRING_DATASOURCE_USERNAME: sajid
      SPRING_DATASOURCE_PASSWORD: sajid123
